language: generic

dist: trusty
sudo: false

matrix:
  include:
    # 3 package variants on major Tcl releases mixed with 2 install variants
    # run tests in code coverage mode on first installation variant
    # for each Tcl releases
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.4 --prefix=/tmp/modules-tcl' MAKE_TESTCOVERAGE='y'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.4
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.5 --prefix=/tmp/modules-tcl' MAKE_TESTCOVERAGE='y'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.5
    # also enable a display on this test case to validate x-resource behavior
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --prefix=/tmp/modules-tcl' MAKE_TESTCOVERAGE='y'
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6

    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.4 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.4
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.5 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.5
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - dejagnu
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6


    # 1 package variation with environment-modules installed
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/modules/init/ --with-loadedmodules=null:dot'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - environment-modules
            - dejagnu
            - man-db
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6

    - env: OS_VERSION=6 DOCKER_IMAGE=centos:centos${OS_VERSION} CONTAINER=centos${OS_VERSION} CMD_PREFIX="docker exec --env RUNTESTFLAGS=-v $CONTAINER"
      sudo: required
      services:
        - docker

    - env: OS_VERSION=7 DOCKER_IMAGE=centos:centos${OS_VERSION} CONTAINER=centos${OS_VERSION} CMD_PREFIX="docker exec --env RUNTESTFLAGS=-v $CONTAINER"
      sudo: required
      services:
        - docker

    - env: OS_VERSION=6 DOCKER_IMAGE=centos:centos${OS_VERSION} CONTAINER=centos${OS_VERSION} CMD_PREFIX="docker exec --env RUNTESTFLAGS=-v $CONTAINER"
           EXTRA_PKGS='environment-modules' CONFIGURE_OPTS='--prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/Modules/init/ --with-loadedmodules=null:dot'
      sudo: required
      services:
        - docker

    - env: OS_VERSION=7 DOCKER_IMAGE=centos:centos${OS_VERSION} CONTAINER=centos${OS_VERSION} CMD_PREFIX="docker exec --env RUNTESTFLAGS=-v $CONTAINER"
           EXTRA_PKGS='environment-modules' CONFIGURE_OPTS='--prefix=/tmp/modules-tcl --enable-set-switchml --with-cver-initdir=/usr/share/Modules/init/ --with-loadedmodules=null:dot'
      sudo: required
      services:
        - docker


env:
  global:
    - RUNTESTFLAGS='-v'
    - CMD_PREFIX=''
    - EXTRA_PKGS=''

install: true

before_install: |
  if [ -n "$DOCKER_IMAGE" ]; then
    docker pull $DOCKER_IMAGE &&
    docker run --name $CONTAINER --detach --rm -i -t -w /modules-tcl $DOCKER_IMAGE /bin/bash &&
    docker exec $CONTAINER yum install -y tcsh zsh ksh tcl make wget perl perl-podlators git dejagnu man-db $EXTRA_PKGS &&
    docker exec $CONTAINER wget -O /etc/yum.repos.d/shells_fish_release_2.repo http://download.opensuse.org/repositories/shells:fish:release:2/CentOS_${OS_VERSION}/shells:fish:release:2.repo &&
    docker exec $CONTAINER yum install -y fish &&
    docker cp ./. $CONTAINER:modules-tcl
  else
    true
  fi

script:
  - $CMD_PREFIX ./configure $CONFIGURE_OPTS
  - $CMD_PREFIX make
  - if [ "$MAKE_TESTCOVERAGE" = 'y' ]; then $CMD_PREFIX make testcoverage; fi
  - if [ "$MAKE_TESTCOVERAGE" != 'y' ]; then $CMD_PREFIX make test; fi
  - $CMD_PREFIX make install
  - $CMD_PREFIX make testinstall
  - $CMD_PREFIX make uninstall

# report code coverage results
after_success: |
  [ "$MAKE_TESTCOVERAGE" = 'y' ] &&
  contrib/nglfar2ccov modulecmd.tcl &&
  bash <(curl -s https://codecov.io/bash) -s coverage

after_script: |
  [ -n "$DOCKER_IMAGE" ] &&
  docker stop $CONTAINER
