language: generic

git:
  depth: false

branches:
  except:
    - c-master
    - c-3.2

os: linux
dist: xenial

jobs:
  include:
    # also enable a display on this test case to validate x-resource behavior
    # check auto handling feature on this test configuration
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --disable-libtclenvmodules --prefix=/tmp/modules --with-pager=more --with-pager-opts=-X --enable-auto-handling' COVERAGE='y'
           EXTRA_SCRIPT_PRETEST='make install-testmodulerc install-testetcrc install-testmodspath-empty' EXTRA_SCRIPT_POSTTEST='make uninstall-testconfig'
      services:
        - xvfb
      before_script:
        - export DISPLAY=:99.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - expect-dev
            - dejagnu
            - python-sphinx
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6
            - perl
            - python
            - ruby
            - cmake
            - r-base-core

    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.4 --prefix=/tmp/modules --disable-libtclenvmodules --enable-compat-version --with-tcl=/usr/lib/tcl8.4 --enable-versioning --disable-silent-shell-debug-support --disable-set-shell-startup --disable-quarantine-support --with-initconf-in=etcdir --with-loadedmodules=null:dot --without-pager --disable-avail-indepth --with-terminal-background=light --with-unload-match-order=returnfirst --disable-implicit-default --with-search-match=contains --with-locked-configs=extra_siteconfig' COVERAGE='y'
           EXTRA_SCRIPT_PRETEST='make install-testinitrc install-testsiteconfig' EXTRA_SCRIPT_POSTTEST='make uninstall-testconfig'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - expect-dev
            - dejagnu
            - python-sphinx
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.4
            - perl
            - python
            - ruby
            - cmake
            - r-base-core
            # libtclenvmodules and compatibility version build requirements
            - gcc
            - autoconf
            - tcl8.4-dev
            # compatibility version-specific build requirements
            - automake
            - autopoint
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.5 --prefix=/tmp/modules --enable-compat-version --with-tcl=/usr/lib/tcl8.5 --disable-quarantine-support --enable-dotmodulespath --with-pager=more --with-dark-background-colors=hi --with-locked-configs=implicit_default --enable-wa-277 --enable-advanced-version-spec --disable-ml --disable-implicit-requirement' COVERAGE='y'
           EXTRA_SCRIPT_PRETEST='make install-testmodulerc-1 install-testetcrc install-testmodspath' EXTRA_SCRIPT_POSTTEST='make uninstall-testconfig'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - expect-dev
            - dejagnu
            - python-sphinx
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.5
            - perl
            - python
            - ruby
            - cmake
            - r-base-core
            # libtclenvmodules and compatibility version build requirements
            - gcc
            - autoconf
            - tcl8.5-dev
            # compatibility version-specific build requirements
            - automake
            - autopoint
    # install specific siteconfig file before test to trigger specific behaviors
    # content of this specific siteconfig is activated by defining a TESTSUITE_ENABLE_SITECONFIG env var
    # siteconfig is deactivated for testinstall suite, will be handled locally in this test suite
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.6 --prefix=/tmp/modules --libdir=/tmp/modules/lib64 --enable-multilib-support' COVERAGE='y' COVERAGE_OLDTCL='y' COVERAGE_MULTILIB='y'
           EXTRA_SCRIPT_PRETEST='make install-testsiteconfig-1 && export TESTSUITE_ENABLE_SITECONFIG=1'
           EXTRA_SCRIPT_POSTTEST='unset TESTSUITE_ENABLE_SITECONFIG'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - expect-dev
            - dejagnu
            - python-sphinx
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.6
            - perl
            - python
            - ruby
            - cmake
            - r-base-core
            # libtclenvmodules build requirements
            - gcc
            - autoconf
            - tcl8.6-dev
    - env: CONFIGURE_OPTS='--with-tclsh=tclsh8.4 --prefix=/tmp/modules --with-tcl=/usr/lib/tcl8.4' COVERAGE='y'
           EXTRA_SCRIPT_PRETEST='make install-testsiteconfig-1 && export TESTSUITE_ENABLE_SITECONFIG=1'
           EXTRA_SCRIPT_POSTTEST='unset TESTSUITE_ENABLE_SITECONFIG'
      addons:
        apt:
          sources:
            - sourceline: 'ppa:fish-shell/release-2'
          packages:
            - expect-dev
            - dejagnu
            - python-sphinx
            - bash
            - tcsh
            - ksh
            - zsh
            - fish
            - tcl8.4
            - perl
            - python
            - ruby
            - cmake
            - r-base-core
            # libtclenvmodules build requirements
            - gcc
            - autoconf
            - tcl8.4-dev


env:
  global:
    - RUNTESTFLAGS='-v'

install: true

script:
  - ./configure $CONFIGURE_OPTS
  - make
  - if [ -n "$EXTRA_SCRIPT_PRETEST" ]; then eval $EXTRA_SCRIPT_PRETEST; fi
  - travis_retry make test-deps
  - travis_wait 30 unbuffer script/mt --base64-failed-log
  - if [ -n "$EXTRA_SCRIPT_POSTTEST" ]; then eval $EXTRA_SCRIPT_POSTTEST; fi
  - make install
  - script/mt --base64-failed-log install
  - make uninstall
  - if [ -n "$EXTRA_SCRIPT_POSTINST" ]; then $EXTRA_SCRIPT_POSTINST; fi

# report code coverage results
after_success: |
  [ "$COVERAGE" = 'y' ] &&
  script/nglfar2ccov modulecmd-test.tcl &&
  bash <(curl -s https://codecov.io/bash)
